# Generated by Django 5.0.3 on 2025-04-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='phone_number',
            new_name='mobile_number',
        ),
    ]
