# Generated by Django 5.0.3 on 2025-04-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_fullname_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.TextField(default=''),
        ),
    ]
