# Generated by Django 5.0.3 on 2025-04-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_featured_img_course_technologies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
    ]
