# Generated by Django 5.0.3 on 2025-04-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_course_average_rating_course_total_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_images/'),
        ),
    ]
