# Generated by Django 5.0.3 on 2025-04-26 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teacher_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile_img',
        ),
        migrations.CreateModel(
            name='StudentFavoriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_courses', to='main.student')),
            ],
            options={
                'ordering': ['-date_added'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
