# Generated by Django 5.0.3 on 2025-04-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_teacher_profile_img_studentfavoritecourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFavoriteCourse',
        ),
    ]
