# Generated by Django 5.0.3 on 2025-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
