# Generated by Django 5.0.2 on 2025-05-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_studymaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '16.FAQs',
            },
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '9.Assignments'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['id'], 'verbose_name_plural': '4.Chapters'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3.Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2.Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'verbose_name_plural': '11.Course Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='courserating',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': '7.Course Ratings'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '14.Notifications'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '10.Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name_plural': '10.Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['fullname'], 'verbose_name_plural': '5.Students'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '6.Student Course Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='studentfavoritecourse',
            options={'ordering': ['-date_added'], 'verbose_name_plural': '8.Student Favorite Courses'},
        ),
        migrations.AlterModelOptions(
            name='studentquizattempt',
            options={'ordering': ['-attempted_at'], 'verbose_name_plural': '12.Student Quiz Attempts'},
        ),
        migrations.AlterModelOptions(
            name='studentquizresponse',
            options={'verbose_name_plural': '13.Student Quiz Responses'},
        ),
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'verbose_name_plural': '15.Study Materials'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name'], 'verbose_name_plural': '1.Teachers'},
        ),
    ]
