# Generated by Django 4.2.7 on 2025-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_teacherstudentchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstudentchat',
            name='message_from',
            field=models.CharField(default='student', max_length=100),
            preserve_default=False,
        ),
    ]
