# Generated by Django 4.2.7 on 2025-05-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_add_message_from_field_manually'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudentchat',
            name='message_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
