# Generated by Django 5.0 on 2026-01-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
