# Generated by Django 5.0 on 2026-01-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_studentcourseenrollment_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to='main.student')),
            ],
            options={
                'verbose_name_plural': '22. Student Chapter Progress',
                'unique_together': {('student', 'chapter')},
            },
        ),
    ]
