# Generated by Django 5.0 on 2026-01-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_studentchapterprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
